# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

name: ${PROJECT_NAME}

services:
  isa:
    image: ${SRV_IMAGE_NAME}
    container_name: ${SRV_CONTAINER_NAME}
    hostname: ${SRV_HOSTNAME}
    ports:
      - ${SRV_PORT}:80
    volumes:
      - ${PROJECT_DIR}/test:/test
      - ${PROJECT_DIR}/app/isa:/usr/local/isa
      - ${PROJECT_DIR}/app/modules:/usr/local/modules
      - ${PROJECT_DIR}/app/configs:/usr/local/configs
      - ${PROJECT_DIR}/infra:/var/local/infra
      - ${PROJECT_DIR}/conf/docker/docker-compose-nginx-lb.yml:/var/local/infra/host/docker-compose.yml
      - ${PROJECT_DIR}/cache/docker-compose-nginx-lb.env:/var/local/infra/host/docker-compose.env
      - "//var/run/docker.sock:/var/run/docker.sock"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /test
    networks:
      - srv-network

  loadbalancer:
    image: nginx
    container_name: ${SRV_CONTAINER_NAME}-lb-default
    ports:
      - 8081:80
    volumes:
      - ${PROJECT_DIR}/infra/loadbalancer/conf.d:/etc/nginx/conf.d:ro
    networks:
      - srv-network

  worker1:
    image: nginx
    container_name: ${SRV_CONTAINER_NAME}-w1
    volumes:
      - ${PROJECT_DIR}/infra/worker1/conf.d:/etc/nginx/conf.d:ro
    networks:
      - srv-network

  worker2:
    image: nginx
    container_name: ${SRV_CONTAINER_NAME}-w2
    volumes:
      - ${PROJECT_DIR}/infra/worker2/conf.d:/etc/nginx/conf.d:ro
    networks:
      - srv-network


networks:
  srv-network:
    driver: bridge
    name: ${INFRA_DOCKER_NETWORK}
    external: true
