# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

name: ${PROJECT_NAME}

services:
  isa:
    image: ${SRV_IMAGE_NAME}
    container_name: ${SRV_CONTAINER_NAME}
    hostname: ${SRV_HOSTNAME}
    ports:
      - ${SRV_PORT}:80
    volumes:
      - ${PROJECT_DIR}/test:/test
      - ${PROJECT_DIR}/app/isa:/usr/local/isa
      - ${PROJECT_DIR}/app/modules:/usr/local/modules
      - ${PROJECT_DIR}/app/configs:/usr/local/configs
      - ${PROJECT_DIR}/infra:/var/local/infra
      - ${PROJECT_DIR}/conf/docker/docker-compose-autoscaling.yml:/var/local/infra/host/docker-compose.yml
      - ${PROJECT_DIR}/cache/docker-compose-autoscaling.env:/var/local/infra/host/docker-compose.env
      - "//var/run/docker.sock:/var/run/docker.sock"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /test
    networks:
      - srv-network

  loadbalancer:
    image: nginx
    container_name: ${SRV_CONTAINER_NAME}-loadbalancer
    volumes:
      - ${PROJECT_DIR}/infra/loadbalancer-to-docekr-scaling/conf.d:/etc/nginx/conf.d:ro
    networks:
      - srv-network

  autoworker:
    image: nginx
    volumes:
      - ${PROJECT_DIR}/infra/worker/conf.d:/etc/nginx/conf.d:ro
    deploy:
      endpoint_mode: vip
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    networks:
      - srv-network

networks:
  srv-network:
    driver: bridge
    name: ${INFRA_DOCKER_NETWORK}
    external: true
